/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.manuel.cronometros.view;

import dev.manuel.cronometros.control.ChronometerController;

/**
 *
 * @author dev_manuel
 */
public class ChronometerPanel extends javax.swing.JPanel {

  private final Integer control;
  private Integer delay;

  private ChronometerController chronometerController;
  /**
   * Creates new form ChronometerPanel
   */
  public ChronometerPanel() {
    initComponents();
    this.control = 1;
    this.btnPlay.setEnabled(true);
    this.btnPause.setEnabled(false);
    this.btnResume.setEnabled(false);
    this.btnRestart.setEnabled(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblCounter = new javax.swing.JLabel();
    btnPlay = new javax.swing.JButton();
    btnPause = new javax.swing.JButton();
    btnResume = new javax.swing.JButton();
    btnRestart = new javax.swing.JButton();
    lblDelay = new javax.swing.JLabel();

    lblCounter.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
    lblCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblCounter.setText("00:00:00:00");

    btnPlay.setText("Play");
    btnPlay.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPlayActionPerformed(evt);
      }
    });

    btnPause.setText("Pause");
    btnPause.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPauseActionPerformed(evt);
      }
    });

    btnResume.setText("Resume");
    btnResume.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnResumeActionPerformed(evt);
      }
    });

    btnRestart.setText("Restart");
    btnRestart.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRestartActionPerformed(evt);
      }
    });

    lblDelay.setText("0 Seconds");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblCounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnPlay)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnPause)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnResume)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnRestart))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(lblDelay)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnPlay)
          .addComponent(btnPause)
          .addComponent(btnResume)
          .addComponent(btnRestart))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(lblDelay)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
    this.chronometerController = new ChronometerController(this.lblCounter, this.lblDelay, this.delay, this.control);
    this.chronometerController.start();
    this.btnPlay.setEnabled(false);
    this.btnPause.setEnabled(true);
    this.btnResume.setEnabled(false);
    this.btnRestart.setEnabled(true);
  }//GEN-LAST:event_btnPlayActionPerformed

  private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
    chronometerController.setControl(-1);
    this.btnPlay.setEnabled(false);
    this.btnPause.setEnabled(false);
    this.btnResume.setEnabled(true);
    this.btnRestart.setEnabled(true);
  }//GEN-LAST:event_btnPauseActionPerformed

  private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
    chronometerController.setControl(1);
    this.btnPlay.setEnabled(false);
    this.btnPause.setEnabled(true);
    this.btnResume.setEnabled(false);
    this.btnRestart.setEnabled(true);
  }//GEN-LAST:event_btnResumeActionPerformed

  private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
    chronometerController.setControl(0);
    this.btnPlay.setEnabled(true);
    this.btnPause.setEnabled(false);
    this.btnResume.setEnabled(false);
    this.btnRestart.setEnabled(false);
    chronometerController.restartCounter();
  }//GEN-LAST:event_btnRestartActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnPause;
  private javax.swing.JButton btnPlay;
  private javax.swing.JButton btnRestart;
  private javax.swing.JButton btnResume;
  private javax.swing.JLabel lblCounter;
  private javax.swing.JLabel lblDelay;
  // End of variables declaration//GEN-END:variables

  /**
   * @param delay the delay to set
   */
  public void setDelay(Integer delay) {
    this.delay = delay;
  }
}
